const MAIN = "#3a6de4";
const CONTRAST = "#fffdc8";
const DISABLED_TEXT = "#303030";

const MAIN_BARD = "#e43a6d";
const CONSTRAST_BARD = "#ffd8c8";
const HIGHLIGHT_BARD = "#ffa500";
const ERROR_BARD = "#ff0000";
const SUCCESS_BARD = "#00ff00";
const DISABLED_BARD = "#606060";

const MAIN_ROGUE = "#3de43a";
const CONTRAST_ROGUE = "#c8ffd8";
const HIGHLIGHT_ROGUE = "#50fa7b";
const ERROR_ROGUE = "#ff5555";
const SUCCESS_ROGUE = "#50fa7b";
const DISABLED_ROGUE = "#606060";

const MAIN_WIZARD = "#e43adf";
const CONTRAST_WIZARD = "#ffc8f8";
const HIGHLIGHT_WIZARD = "#ff79c6";
const ERROR_WIZARD = "#ff6ac1";
const SUCCESS_WIZARD = "#8be9fd";
const DISABLED_WIZARD = "#606060";

export const THEME_BARD = {
  MAIN: MAIN_BARD,
  CONTRAST: CONSTRAST_BARD,
  HIGHLIGHT: HIGHLIGHT_BARD,
  ERROR: ERROR_BARD,
  SUCCESS: SUCCESS_BARD,
  DISABLED: DISABLED_BARD
};

export const THEME_ROGUE = {
  MAIN: MAIN_ROGUE,
  CONTRAST: CONTRAST_ROGUE,
  HIGHLIGHT: HIGHLIGHT_ROGUE,
  ERROR: ERROR_ROGUE,
  SUCCESS: SUCCESS_ROGUE,
  DISABLED: DISABLED_ROGUE
};

export const THEME_WIZARD = {
  MAIN: MAIN_WIZARD,
  CONTRAST: CONTRAST_WIZARD,
  HIGHLIGHT: HIGHLIGHT_WIZARD,
  ERROR: ERROR_WIZARD,
  SUCCESS: SUCCESS_WIZARD,
  DISABLED: DISABLED_WIZARD
};

export const THEMES = {
  BARD: THEME_BARD,
  ROGUE: THEME_ROGUE,
  WIZARD: THEME_WIZARD
};

export default { MAIN, CONTRAST, DISABLED_CONTRAST: DISABLED_TEXT, THEME_BARD, THEME_ROGUE, THEME_WIZARD, THEMES };

